# Module1-Ex3 - Getting and Knowing your Data

- Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries and read the dataset `chipo.csv`

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('chipo.csv')

### Step 2. See the first 10 entries

In [3]:
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 3. What is the number of observations in the dataset?

In [7]:
# Solution 2
print(f"There are {df.shape[0]} observation in the dataset")

There are 4622 observation in the dataset

In [8]:
df.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 4. What is the number of columns in the dataset?

In [11]:
print(f"there are {df.shape[1]} number of colums")

there are 5 number of colums

### Step 5. Print the name of all the columns.

In [13]:
list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

### Step 6. How is the dataset indexed?

In [14]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [15]:
df[:10] #first ten observation

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [16]:
df.loc[2] #this uses the index value 2

order_id                             1
quantity                             1
item_name             Nantucket Nectar
choice_description             [Apple]
item_price                      $3.39
Name: 2, dtype: object

In [17]:
df2 = df # this points to the same location
df2 = df.copy() #this is a shallow copy

In [18]:
df2.drop(2, axis = 0, inplace= True) #2 searches axis = 0 means a row axis = 1 means a column

In [19]:
df2[:10]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45

In [21]:
df2.loc[3] # index of the row
df2.iloc[2] # order of the row

order_id                                                  1
quantity                                                  1
item_name             Chips and Tomatillo-Green Chili Salsa
choice_description                                      NaN
item_price                                           $2.39
Name: 3, dtype: object

In [26]:
df2.set_index('order_id', inplace= True)

KeyError: "None of ['order_id'] are in the columns"

In [24]:
df2.reset_index()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
3,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
4,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
...,...,...,...,...,...
4616,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4618,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 7. Which was the most-ordered item?

In [27]:
df[:10]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [32]:
df.groupby('item_name').sum()

,order_id,quantity,choice_description,item_price
item_name,,,,
6 Pack Soft Drink,52322,55,[Sprite][Diet Coke][Coke][Diet Coke][Diet Coke...,$6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.4...
Barbacoa Bowl,53972,66,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75 $11.75 $9.25 $8.99 $9.25 $11.75 $9.25 $...
Barbacoa Burrito,74718,91,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99 $9.25 $9.25 $11.75 $11.75 $9.25 $8.99 $1...
Barbacoa Crispy Tacos,5613,12,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75 $9.25 $11.48 $11.75 $9.25 $9.25 $8.99 $...
Barbacoa Salad Bowl,9708,10,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89 $11.89 $9.39 $9.39 $9.39 $11.89 $11.89 ...
Barbacoa Soft Tacos,18725,25,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$9.25 $9.25 $8.99 $9.25 $9.25 $11.75 $11.75 $9...
Bottled Water,175944,211,0,$1.09 $1.09 $1.09 $1.50 $1.50 $1.50 $3.00 $1.5...
Bowl,472,4,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20 $7.40
Burrito,1550,6,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",$7.40 $7.40 $7.40 $7.40 $7.40 $7.40
Canned Soda,76396,126,[Sprite][Dr. Pepper][Mountain Dew][Sprite][Dr....,$2.18 $1.09 $2.18 $1.09 $1.09 $1.09 $1.09 $2.1...
Canned Soft Drink,304753,351,[Coke][Sprite][Coke][Coke][Lemonade][Sprite][D...,$1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.2...
Carnitas Bowl,62742,71,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $11.75 $9.25 $11.48 $8.99 $8.99 $23.50 $...
Carnitas Burrito,51652,60,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99 $9.25 $11.75 $9.25 $9.25 $9.25 $11.75 $9...
Carnitas Crispy Tacos,5868,8,[Roasted Chili Corn Salsa][Tomatillo Green Chi...,$9.25 $11.75 $8.99 $11.75 $8.99 $17.98 $9.25
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
Carnitas Salad Bowl,6693,6,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89 $9.39 $11.89 $9.39 $11.89 $11.89
Carnitas Soft Tacos,37673,40,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$9.25 $9.25 $9.25 $9.25 $9.25 $8.99 $8.99 $8.9...
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...
Chicken Burrito,497303,591,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49 $8.49 $10.98 $8.49 $10.98 $10.98 $8.75 $...
Chicken Crispy Tacos,47382,50,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75 $17.50 $11.25 $8.49 $8.49 $11.25 $8.75 $...
Chicken Salad,10465,9,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98 $10.98 $8.49 $8.49 $8.49 $8.49 $8.49 $8...
Chicken Salad Bowl,117104,123,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75 $22.50 $22.50 $8.75 $17.50 $8.75 $8.75 $...
Chicken Soft Tacos,98395,120,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75 $8.75 $8.75 $8.75 $11.25 $8.49 $8.49 $8....
Chips,208004,230,0,$2.15 $2.15 $2.15 $2.15 $2.15 $2.15 $4.30 $2.1...
Chips and Fresh Tomato Salsa,100419,130,0,$2.39 $2.39 $2.39 $2.95 $2.95 $2.95 $2.95 $2.3...
Chips and Guacamole,449959,506,0,$4.45 $4.45 $4.45 $4.45 $4.45 $3.99 $4.45 $3.9...
Chips and Mild Fresh Tomato Salsa,279,1,0,$3.00
Chips and Roasted Chili Corn Salsa,14999,23,0,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Chips and Roasted Chili-Corn Salsa,17462,18,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Chips and Tomatillo Green Chili Salsa,41170,45,0,$2.95 $2.95 $5.90 $2.95 $2.95 $2.95 $2.95 $2.9...
Chips and Tomatillo Red Chili Salsa,45556,50,0,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Chips and Tomatillo-Green Chili Salsa,21826,33,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Chips and Tomatillo-Red Chili Salsa,18344,25,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Crispy Tacos,434,2,[Adobo-Marinated and Grilled Steak][Adobo-Mari...,$7.40 $7.40
Izze,10587,20,[Clementine][Grapefruit][Blackberry][Blackberr...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.3...
Nantucket Nectar,21814,29,[Apple][Pomegranate Cherry][Pineapple Orange B...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $6.78 $3.3...
Salad,1150,2,"[Brown Rice, Adobo-Marinated and Grilled Chick...",$7.40 $7.40
Side of Chips,84769,110,0,$1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.6...
Steak Bowl,193752,221,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.99 $8.99 $11.75 $11.75 $8.99 $11.48 $9.25 $...
Steak Burrito,328437,386,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75 $9.25 $8.99 $11.75 $8.99 $8.99 $8.99 $8...
Steak Crispy Tacos,35818,36,"[Fresh Tomato Salsa, Sour Cream][[Roasted Chil...",$9.25 $8.99 $9.25 $8.69 $8.99 $9.25 $8.99 $9.2...
Steak Salad,2362,4,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $8.99 $8.99 $8.69
Steak Salad Bowl,29590,31,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$23.78 $11.89 $9.39 $23.78 $11.89 $11.89 $11.8...
Steak Soft Tacos,50177,56,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25 $9.25 $8.99 $9.25 $8.99 $8.99 $9.25 $9.2...
Veggie Bowl,72270,87,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $8.49 $11.25 $11.25 $8.49 $11.25 $11.25...
Veggie Burrito,80962,97,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.49 $11.25 $11.25 $10.98 $8.49 $8.49 ...
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49
Veggie Salad,7265,6,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49 $8.49 $8.49 $8.49 $8.49 $8.49
Veggie Salad Bowl,17303,18,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $11.25 $11.25 $11.25 $8.75 $8.75 $11.25...
Veggie Soft Tacos,5520,8,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.75 $8.49 $11.25 $8.75 $8.49 $16.98

In [33]:
df[['item_name','quantity']].groupby('item_name').sum()

                                       quantity
item_name
6 Pack Soft Drink                            55
Barbacoa Bowl                                66
Barbacoa Burrito                             91
Barbacoa Crispy Tacos                        12
Barbacoa Salad Bowl                          10
Barbacoa Soft Tacos                          25
Bottled Water                               211
Bowl                                          4
Burrito                                       6
Canned Soda                                 126
Canned Soft Drink                           351
Carnitas Bowl                                71
Carnitas Burrito                             60
Carnitas Crispy Tacos                         8
Carnitas Salad                                1
Carnitas Salad Bowl                           6
Carnitas Soft Tacos                          40
Chicken Bowl                                761
Chicken Burrito                             591
Chicken Crispy Tacos                         50
Chicken Salad                                 9
Chicken Salad Bowl                          123
Chicken Soft Tacos                          120
Chips                                       230
Chips and Fresh Tomato Salsa                130
Chips and Guacamole                         506
Chips and Mild Fresh Tomato Salsa             1
Chips and Roasted Chili Corn Salsa           23
Chips and Roasted Chili-Corn Salsa           18
Chips and Tomatillo Green Chili Salsa        45
Chips and Tomatillo Red Chili Salsa          50
Chips and Tomatillo-Green Chili Salsa        33
Chips and Tomatillo-Red Chili Salsa          25
Crispy Tacos                                  2
Izze                                         20
Nantucket Nectar                             29
Salad                                         2
Side of Chips                               110
Steak Bowl                                  221
Steak Burrito                               386
Steak Crispy Tacos                           36
Steak Salad                                   4
Steak Salad Bowl                             31
Steak Soft Tacos                             56
Veggie Bowl                                  87
Veggie Burrito                               97
Veggie Crispy Tacos                           1
Veggie Salad                                  6
Veggie Salad Bowl                            18
Veggie Soft Tacos                             8

In [35]:
df[['item_name','quantity']].groupby('item_name').sum().sort_values(by='quantity', ascending= False)

                                       quantity
item_name
Chicken Bowl                                761
Chicken Burrito                             591
Chips and Guacamole                         506
Steak Burrito                               386
Canned Soft Drink                           351
Chips                                       230
Steak Bowl                                  221
Bottled Water                               211
Chips and Fresh Tomato Salsa                130
Canned Soda                                 126
Chicken Salad Bowl                          123
Chicken Soft Tacos                          120
Side of Chips                               110
Veggie Burrito                               97
Barbacoa Burrito                             91
Veggie Bowl                                  87
Carnitas Bowl                                71
Barbacoa Bowl                                66
Carnitas Burrito                             60
Steak Soft Tacos                             56
6 Pack Soft Drink                            55
Chicken Crispy Tacos                         50
Chips and Tomatillo Red Chili Salsa          50
Chips and Tomatillo Green Chili Salsa        45
Carnitas Soft Tacos                          40
Steak Crispy Tacos                           36
Chips and Tomatillo-Green Chili Salsa        33
Steak Salad Bowl                             31
Nantucket Nectar                             29
Chips and Tomatillo-Red Chili Salsa          25
Barbacoa Soft Tacos                          25
Chips and Roasted Chili Corn Salsa           23
Izze                                         20
Veggie Salad Bowl                            18
Chips and Roasted Chili-Corn Salsa           18
Barbacoa Crispy Tacos                        12
Barbacoa Salad Bowl                          10
Chicken Salad                                 9
Carnitas Crispy Tacos                         8
Veggie Soft Tacos                             8
Burrito                                       6
Carnitas Salad Bowl                           6
Veggie Salad                                  6
Bowl                                          4
Steak Salad                                   4
Salad                                         2
Crispy Tacos                                  2
Carnitas Salad                                1
Chips and Mild Fresh Tomato Salsa             1
Veggie Crispy Tacos                           1

In [36]:
df[['item_name','quantity']].groupby('item_name').sum().sort_values(by='quantity', ascending= False).head(1)

              quantity
item_name
Chicken Bowl       761

In [39]:
df[['item_name','quantity']].groupby('item_name').sum().sort_values(by='quantity', ascending= False)[:1]

              quantity
item_name
Chicken Bowl       761

In [40]:
df[['item_name','quantity']].groupby('item_name').sum().sort_values(by='quantity', ascending= False).iloc[0]

quantity    761
Name: Chicken Bowl, dtype: int64

In [41]:
df[['item_name','quantity']].groupby('item_name').sum().sort_values(by='quantity', ascending= False).index[0]

'Chicken Bowl'

In [47]:
df[['item_name','quantity']].groupby('item_name').sum().sort_values(by='quantity', ascending= False).iloc[0].quantity

np.int64(761)

In [43]:
df[['item_name','quantity']].groupby('item_name').sum().sort_values(by='quantity', ascending= False).values[0][0]

np.int64(761)

### Step 8. For the most-ordered item, how many items were ordered?

### Step 9. What was the most ordered item in the choice_description column?

### Step 10. How many items were orderd in total?

In [50]:
#total number of orders or different items
#assuming order_id is sorted
df.sort_values(by="order_id", ascending= False).iloc[0,0]

np.int64(1834)

In [52]:
df['item_name'].unique()
len(df['item_name'].unique())

50

### Step 11. Turn the item price into a float

#### Step 11.a. Check the item price type

In [53]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [54]:
df['item_price']

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

In [55]:
df['item_price'].dtype

dtype('O')

#### Step 11.b. Create a lambda function and change the type of item price

In [56]:
df['item_price'][:10]

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
5    $10.98
6     $1.69
7    $11.75
8     $9.25
9     $9.25
Name: item_price, dtype: object

In [61]:
elim_dollar = lambda x:float(x[1:])

df['item_price'] = df['item_price'].apply(elim_dollar)

In [60]:
inv_dollar = lambda x: '$' +str(x)
df['item_price'] = df['item_price'].apply(inv_dollar)

#### Step 11.c. Check the item price type

### Step 12. How much was the revenue for the period in the dataset?

In [62]:
df[:3]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39

In [64]:
(df['quantity'] * df['item_price']).sum()

np.float64(39237.02)

### Step 13. How many orders were made in the period?

### Step 14. What is the average revenue amount per order?

In [3]:
# Solution 1

### Step 15. How many different items are sold?